name: Sync Tailscale ACLs

on:
  push:
    branches:
      - main
    paths:
      - 'policy.hujson'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy ACL to Tailscale
        id: tailscale-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          action:apply
          api-key: ${{ secrets.TS_API_KEY }}
          policy-file: policy.hujson
          tailnet: ${{ secrets.TS_TAILNET }}
